[tool.poetry]
name = "your_package_name"
version = "0.1.0"
description = "A short description of your package."
authors = ["Your Name <you@example.com>"]
dependencies = {
tenacity = "^8.0.0",
tiktoken = "^0.5.0"
}